// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFKzuJloUNMsmzmkprR-QfVZ71-BvbR64',
    appId: '1:434444429726:web:27ea7fb36de31de8c70e8f',
    messagingSenderId: '434444429726',
    projectId: 'coffee-app-a26c5',
    authDomain: 'coffee-app-a26c5.firebaseapp.com',
    storageBucket: 'coffee-app-a26c5.firebasestorage.app',
    measurementId: 'G-DE5G4BGDX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrDwNIGH3HeNCMJWZ1e83-UEoS9OeWuq8',
    appId: '1:434444429726:android:1373f3998cf365d8c70e8f',
    messagingSenderId: '434444429726',
    projectId: 'coffee-app-a26c5',
    storageBucket: 'coffee-app-a26c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgbJfeBfnOJWY5mZaxh5-A3X_F8ATZ5Bk',
    appId: '1:434444429726:ios:f950dbe3bb84a805c70e8f',
    messagingSenderId: '434444429726',
    projectId: 'coffee-app-a26c5',
    storageBucket: 'coffee-app-a26c5.firebasestorage.app',
    iosBundleId: 'com.example.careConnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoC2GiDCWRNAIBq5LloimlD60qoEajbkw',
    appId: '1:434444429726:web:ee185c0538d9fec1c70e8f',
    messagingSenderId: '434444429726',
    projectId: 'coffee-app-a26c5',
    authDomain: 'coffee-app-a26c5.firebaseapp.com',
    storageBucket: 'coffee-app-a26c5.firebasestorage.app',
    measurementId: 'G-3K67G5EWS5',
  );
}
